branch-defaults:
  master:
    environment: null
global:
  application_name: p_kintai
  branch: null
  default_ec2_keyname: egate-pkintai
  default_platform: Ruby 2.4 (Puma)
  default_region: ap-northeast-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: egate
  repository: null
  sc: git
  workspace_type: Application
