version: 2
jobs:
  build:
    docker:
      - image: ruby:2.4.2
      - image: library/mysql:latest
        env:
          - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - image: redis

    working_directory: ~/p_kintai
    steps:
      - checkout
      - run: apt-get update -qq && apt-get install -y build-essential nodejs
      - restore_cache:
          keys:
            - gemfile-{{ checksum "Gemfile.lock" }}
      - run: bundle install --jobs=4 --path=vendor/bundle --without production
      - save_cache:
          key: gemfile-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: bundle exec rubocop
      - run: bundle exec brakeman -5 -A -w 1 -e -z
